Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
  #config.vm.forward_port "http", 8080, 8080

  Vagrant::Config.run do |config|
    #config.vm.provision :puppet, :module_path => "modules"
    
    # TODO: apt-get update to run....
    config.vm.provision :puppet do |puppet|
      puppet.module_path = "modules"
      # defaul manifest path: manifests
      #puppet.manifests_path = "manifests"
      puppet.manifest_file = "newbox.pp"
    end
  end

end
