Vagrant::Config.run do |config|
  #this box was made with rvm_basebox
  config.vm.box = "rvm-ubu1010"
  config.vm.customize do |vm|
    # see how much faster this is ... or not
    vm.memory_size = 512 #1024
  end
  path="varcacheapt"
  if File.exists?(path) && File.directory?(path)
    #puts("DD:apt-cache found directory #{path} mounting as /var/cache/apt")
    config.vm.share_folder "v-aptcache", "/var/cache/apt", "../varcacheapt"
  #else puts("DD:apt-cache directory #{path} not found to mount as /var/cache/apt")
  end
  config.vm.network("192.168.11.11")
  
  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path =  ["cookbooks", "../fnicholcookbooks"]

    # does all the magic.
    chef.add_recipe("vagrant_main")
    #   chef.add_recipe "mysql"
    #   chef.add_role "web"
    #   # You may also specify custom JSON attributes:
    #chef.json = { :mysql_password => "foo" }
    chef.json.merge!({
      :ubuntu=> {
        :archive_url  => "http://ca.archive.ubuntu.com/ubuntu"
      },
      :mysql => {
        :server_root_password => 'mysekret'
      },
      #:rvm => {
      #    :default_ruby             => "ruby-1.9.2-p180"
      #},
      :iptables => {
          :status                   => "enable"
      },
      :nginx => {
          :iptables_ports           => [ 80, 443 ],
          :extra_configure_flags    => [ "--with-http_sub_module" ]
      },
      :gitorious => {
        :host => 'gitorious.local', 
        :db => {
          :password => 'gitsekret'
        },
        :notification_emails => "daniel.lauzon@gmail.com",
        :support_email => "daniel.lauzon@gmail.com",
        :mailer=>{
          :delivery_method => 'smtp'
        },
        :smtp=>{
          :tls=>"true",          
          :address => "smtp.gmail.com",
          :port => "587",
          :domain => "gmail.com",
          :username => "goedel.relay@gmail.com",
          :password => "PASS",
          :authentication => :plain
        }
      }
    })

  end
end
