Vagrant::Config.run do |config|
  #this box was made with fnichols veewee-definitions
  config.vm.box = "ubuntu-10.10-server-i386"
  #config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
  config.vm.forward_port "http", 80, 8080
  config.vm.forward_port "https", 443, 8443
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"
  
  config.vm.customize do |vm|
    # see how much faster this is ... or not
    vm.memory_size = 512 #1024
  end
  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path =  ["cookbooks", "../fnicholcookbooks"]
    #chef.cookbooks_path =  ["fnicholcookbooks"]

    # does all the magic.
    chef.add_recipe("vagrant_main")
    #   chef.add_recipe "mysql"
    #   chef.add_role "web"
    #   # You may also specify custom JSON attributes:
    #chef.json = { :mysql_password => "foo" }
    chef.json.merge!({
      :mysql => {
        :server_root_password => 'mysekret'
        },
        #:rvm => {
        #    :default_ruby             => "ruby-1.9.2-p180"
        #},
        #:iptables => {
        #    :status                   => "enable"
        #},
        #:nginx => {
        #    :iptables_ports           => [ 80, 443 ],
        #    :extra_configure_flags    => [ "--with-http_sub_module" ]
        #},
        :gitorious => {
          :db=>{
            :password => 'gitsekret'
          }
        }
      })

  end
end
